turnero/turnero/urls.py
import debug_toolbar
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import include, path
from pip._internal.utils.urls import url_to_path

from . import settings

from django.urls import reverse_lazy
from core.turnero_app.models import Persona
from core.turnero_app.views import *
from django.conf.urls.static import static
from core.login.views import LoginFormView
from django.views.generic import TemplateView, RedirectView

from django.contrib.auth.decorators import login_required

from django.contrib.auth.views import LoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('principal/', login_required(PrincipalView.as_view()), name='principal_name'),
    # path('^$', redirect('principal_name')),
    path('', RedirectView.as_view(url=reverse_lazy('principal_name'))),
    # path('principalanterior/', ClienteFormView.as_view(), name='princi_name'),
    # path('principalprueba/', home_view, name='principalea_name'),
    path('principal/vercola/', login_required(VerColaView.as_view()), name='vercola_name'),
    path('principal/cola/', login_required(SoloVerColaView.as_view()), name='solovercola_name'),
    path('login/', LoginFormView.as_view(), name='login'),
    # path('principal/registro', TemplateView.as_view(template_name='body.html'), name='prueba_link'),
    path('principal/turno/', login_required(ServicioView.as_view()), name='turno_name'),
    # path('__debug__/', include('debug_toolbar.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

turnero/core/turnero_app/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
import datetime
from django.db import models

from django.contrib import admin

from .choices import SEXO, PRIORIDAD


# class Cargo(models.Model):
#     cargo_id = models.AutoField(primary_key=True)
#     estado_cargo = models.BooleanField()
#     cargo_descripcion = models.CharField(max_length=25)
#     fecha_insercion = models.DateTimeField(null=True)
#     usuario_modificacion = models.CharField(max_length=16,blank=True,null=True)
#     fecha_modificacion = models.DateTimeField(null=True)
#     usuario_insercion = models.CharField(max_length=16,blank=True,null=True)
#     email = models.EmailField(max_length=254,null=True)

#     def __str__ (self):
#         return self.cargo_descripcion

#     class Meta:
#         db_table = "cargo"


def prioridadNivel(prio):
    if prio.id == 1:
        return "Alta"
    elif prio.id == 2:
        return "Media"
    return "Baja"


def documentoChoices():
    i = 1
    l = []

    for obj in TipoDeDocumento.objects.all():
        k = (i, obj.descripcion)
        l.append(k)
        i = i + 1
    return tuple(l)


class TipoDeDocumento(models.Model):
    id = models.IntegerField(primary_key=True)
    descripcion = models.CharField(unique=True, max_length=64)

    def __str__(self) -> str:
        return self.descripcion
        return str(self.id)

    class Meta:
        db_table = 'Tipo de Documento'


class Persona(models.Model):
    id = models.AutoField(primary_key=True)
    tipo_documento = models.ForeignKey('TipoDeDocumento', on_delete=models.CASCADE)
    nro_documento = models.CharField(unique=True, max_length=16)
    nombre = models.CharField(max_length=64)
    apellido = models.CharField(max_length=64, blank=True, null=True)
    fecha_nacimiento = models.DateField()
    telefono = models.CharField(max_length=32, blank=True, null=True)
    direccion = models.CharField(max_length=128, blank=True, null=True)
    email = models.EmailField(max_length=64, blank=True, null=True)
    # sexo = models.BooleanField(blank=True, null=True)
    sexo = models.CharField(max_length=1, choices=SEXO, default='M')

    def getNombre(self):
        return self.nombre

    def getApellido(self):
        return self.apellido

    def __str__(self):
        return "{} {} {}".format(self.id,self.nombre,self.apellido)
        # return str(self.id) + " " + self.nombre + " " + self.apellido
        # return str(self.id)

    class Meta:
        db_table = 'Persona'


class Usuario(models.Model):
    id = models.AutoField(primary_key=True)
    persona = models.ForeignKey(Persona, on_delete=models.CASCADE)
    fecha_de_registro = models.DateField(default=datetime.date.today)
    ultima_conexion = models.DateTimeField(blank=True, null=True)
    area = models.CharField(max_length=64, blank=True, null=True)
    nombre_usuario = models.CharField(max_length=64)
    contrasena = models.CharField(max_length=64)

    def __str__(self) -> str:
        return self.nombre_usuario
        return str(self.id)

    class Meta:
        db_table = 'Usuario'
        unique_together = (('persona', 'nombre_usuario'),)


class Servicio(models.Model):
    id = models.IntegerField(primary_key=True)
    descripcion = models.CharField(unique=True, max_length=128)

    def getDescripcion(self):
        return self.descripcion

    def __str__(self) -> str:
        return str(self.id)

    class Meta:
        db_table = 'Servicio'


class Box(models.Model):
    id = models.AutoField(primary_key=True)
    descripcion = models.CharField(unique=True, max_length=128)
    servicio = models.ForeignKey('Servicio', on_delete=models.CASCADE)
    estado = models.BooleanField()

    def getDescripcion(self):
        return self.descripcion

    def getServicio(self):
        return self.servicio

    def __str__(self) -> str:
        return str(self.id)

    class Meta:
        verbose_name = "Box"
        verbose_name_plural = "Boxes"
        db_table = 'Box'


class Cliente(models.Model):
    id = models.AutoField(primary_key=True)
    persona = models.OneToOneField('Persona', on_delete=models.CASCADE)

    @admin.display(description='Prioridad')
    def prioridad(self):
        return prioridadNivel(ColaLista.objects.get(cliente=self.id).prioridad)
        pri = (ColaLista.objects.get(cliente=self.id))
        return "Alta" if pri == 1 else "Media" if pri == 2 else "Baja"

    @admin.display(description='En espera',boolean=True)
    def en_espera(self) -> bool:
        return (ColaLista.objects.get(cliente=self.id).en_espera)

    def __str__(self) -> str:
        return str(self.persona)

    class Meta:
        db_table = 'Cliente'


class Cola(models.Model):
    id = models.AutoField(primary_key=True)
    box = models.OneToOneField(Box, on_delete=models.CASCADE)

    @admin.display(description='Box')
    def boxDescripcion(self):
        return "%s" % (self.box.getDescripcion())

    @admin.display(description='Servicio')
    def boxServicioDescripcion(self):
        return "%s" % (self.box.getServicio().getDescripcion())

    def __str__(self) -> str:
        return self.box.servicio.descripcion + " " + self.box.descripcion

    class Meta:
        db_table = 'Cola'


class Prioridad(models.Model):
    id = models.AutoField(primary_key=True)
    descripcion = models.CharField(unique=True, max_length=128)

    def __str__(self) -> str:
        return self.descripcion

    def getprioridad(self):
        return prioridadNivel(self)

    class Meta:
        verbose_name = "Prioridad"
        verbose_name_plural = "Prioridades"
        db_table = 'Prioridad'


def defaultPriority(client):
    # fecha_nacimiento = Persona.objects.get(pk=cliente.persona).fecha_nacimiento
    fecha_nacimiento = Persona.objects.get(pk=client.persona).fecha_nacimiento
    print(fecha_nacimiento)
    d1 = datetime.date.today()
    d2 = fecha_nacimiento
    if int(abs((d1 - d2).days) / 365) >= 65:
        return 1
    else:
        return 3


class ColaLista(models.Model):


    id = models.AutoField(primary_key=True)
    cliente = models.OneToOneField(Cliente, on_delete=models.CASCADE)


    PRIO = (
        (Prioridad.objects.get(pk=1),'ALTA'),
        (Prioridad.objects.get(pk=2),'MEDIA'),
        (Prioridad.objects.get(pk=3),'BAJA'),
    )
    PRIO2 = (
        (Prioridad.objects.get(pk=1).pk,'ALTA'),
        (Prioridad.objects.get(pk=2).pk,'MEDIA'),
        (Prioridad.objects.get(pk=3).pk,'BAJA'),
    )

    cola = models.ForeignKey(Cola, on_delete=models.CASCADE)
    prioridad = models.ForeignKey('Prioridad', default=3,
                                  on_delete=models.CASCADE)
    usuario = models.ForeignKey('Usuario', on_delete=models.CASCADE, null=True, blank=True)
    en_espera = models.BooleanField(default=True)
    hora = models.TimeField(default=datetime.datetime.now().strftime("%H:%M:%S"))

    @admin.display(description='Nombre y Apellido')
    def nombreCompleto(self):
        return "%s %s" % (self.cliente.persona.getNombre(), self.cliente.persona.getApellido())

    @admin.display(description='Box')
    def box(self):
        return "%s" % (self.cola.box.getDescripcion())

    @admin.display(description='Servicio')
    def servicio(self):
        return "%s" % (self.cola.box.servicio.getDescripcion())

    @admin.display(description='Cola')
    def colaid(self):
        return "%s" % (self.cola.id)

    @admin.display(description='Prioridad')
    def prioridadNivel(self):
        return prioridadNivel(self.prioridad)

    def __str__(self) -> str:
        return str(self.id)

    class Meta:
        db_table = 'Cola Lista'

turnero/templates/administrarCola.html
{#{% extends "admin/base.html" %}#}
{% extends "body.html" %}
{% load static %}
{% load widget_tweaks %}
{% load jazzmin %}
<!--Comienzo de la tabla principal -->
{% block content2 %}
    <table class="table table-bordered text-center">
        <tbody>
        <tr>
            <th>
                <p class="text-primary">
                <h2>Ver Cola</h2>
                </p>
            </th>
        </tr>
        <tr>
            <td>
                <button type="button" class="btn btn-block btn-primary btn-lg">Ver Colas</button>
            </td>
        </tr>
        {% comment %}
            <tr>
                <td>
                    <button type="button" class="btn btn-block btn-primary btn-lg">Primary</button>
                </td>
            </tr> {% endcomment %}
        </tbody>
    </table>
    <table class="table table-bordered table-hover">
        <tbody>
        <tr data-widget="expandable-table" aria-expanded="false">
            <td>
                <button type="button" class="btn btn-block btn-primary btn-lg">Ingresar Cliente</button>
            </td>
        </tr>
        <tr class="expandable-body d-none">
            <td colspan="5">
                <h3></h3>
                <div class="input-group mb-3">
                    <input type="text" class="form-control rounded-0" placeholder="Numero de documento"
                           pattern="^[0-9]{6,9}(-[0-9])?\Z">
                    {{ form.text|add_class:'form-control rounded-0'|attr:"placeholder:Numero de documento"|attr:"pattern:[0-9]{6,9}(-[0-9])?\Z"}}
                    <span class="input-group-append">
                                        <button type="button" class="btn btn-info btn-flat">Go!</button>
                                    </span>
                </div>
            </td>
        </tr>
        </tbody>
    </table>

    {#{% block javascript %}
        <script>
            $(function (){
                $('.btn-flat').on('click',function(){
                    $.ajax({
                        url: '{% url 'prueba' %}',
                        type: 'POST',
                        data: {id:1},
                        dataType: 'json'
                    }).done(function (data){

                    })
                })});
        </script>
    {% endblock javascript %}#}
{% endblock content2 %}
<!--Termino de la tabla principal -->

turnero/templates/body.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
{% load jazzmin %}
{% block extrahead %}

{% endblock %}
{% comment %} {% block nav-sidebar %}{% endblock %} {% endcomment %}
{% block content %}
    {% comment %} <h2>Personas</h2>
        <ul>
            {% for persona in persona_list %}
                <li>{{ persona.nombre }}</li>{% endfor %}
        </ul> {% endcomment %}
    <div class="col-md-12">
        {% block cardblock %}
            <div class="card card-header container">
            <div class="card-header">
                {% comment %} <h3 class="card-title">
                    <i class="fas fa-edit"></i>
                    Buttons
                </h3> {% endcomment %}
                <!--Comienzo de la tabla principal -->
                {% block content2 %}
                {% endblock content2 %}
                <!--Termino de la tabla principal -->
            </div>{% endblock cardblock %}
        </div>
    </div>
{% endblock content %}

{% block extrajs %}

    {% block javascript %}

    {% endblock javascript %}

{% endblock extrajs %}

turnero/templates/principal.html
{#{% extends "admin/base.html" %}#}
{% extends "body.html" %}
{% load static %}
{% load widget_tweaks %}
{% load jazzmin %}
<!--Comienzo de la tabla principal -->
{% block content2 %}

    <h3><p class="font-weight-bold text-center">Turnero</p>
    </h3>

    <div id="accordion">
        {#------------------Colas-----------------------#}
        <div class="card">
            <div class="card-header" id="headingOne">
                <h5 class="mb-0">
{#                    <form method="POST">#}
                        <a href="{% url 'vercola_name' %}"> <button type="submit" class="btn btn-block btn-primary btn-lg">Colas
                        </button></a>
{#                    </form>#}
                </h5>
            </div>
        </div>
        {#------------------Ingreso-----------------------#}
        <div class="card">
            <div class="card-header" id="headingOne">
                <h5 class="mb-0">
                    <button type="button" class="btn btn-block btn-primary btn-lg" data-toggle="collapse"
                            data-target="#collapseOne"
                            aria-expanded="{% if client_form.errors %}false{% else %}true{% endif %}"
                            aria-controls="collapseOne">Ingresar
                        Cliente
                    </button>
                </h5>
            </div>
            <div id="collapseOne" class="collapse{% if client_form.errors or client_form.has_changed %} show{% endif %}"
                 aria-labelledby="headingOne"
                 data-parent="#accordion">
                <div class="card-body">


                    <form method="POST">
                        {% csrf_token %}
                        <span class="input-group-append">
                            <input type='hidden' name='action' value='client_nro'>
                        {{ client_form.nro |add_class:"form-control rounded-0"|attr:"placeholder:Numero de documento" }}
                                        <button type="submit" class="btn btn-info btn-flat">Go!</button>
                                    </span>

                        <div class="text-danger">
                            {% if client_form.errors %}

                                {% for field in client_form %}
                                    {% for error in field.errors %}
                                        {{ error }}
                                    {% endfor %}
                                {% endfor %}
                            {% endif %}
                        </div>

                    </form>

                </div>
            </div>
        </div>
        {#------------------Registro-----------------------#}
        <div class="card">
            <div class="card-header" id="headingTwo">
                <h5 class="mb-0">
                    <button type="button" class="btn btn-block btn-primary btn-lg" data-toggle="collapse"
                            data-target="#collapseTwo"
                            aria-expanded="{% if registro_form.errors %}false{% else %}true{% endif %}"
                            aria-controls="collapseTwo">Registrar
                        Cliente
                    </button>
                </h5>
            </div>
            <div id="collapseTwo" class="collapse{% if registro_form.errors %} show{% endif %}"
                 aria-labelledby="headingTwo"
                 data-parent="#accordion">
                <div class="card-body">

                    <form method="post">
                        {% csrf_token %}


                        <div class="row">


                            <div class="col">
                                <div class="card-body">

                                    {% for field in registro_form %}
                                        <div class="form-group">
                                            <div class="row">

                                                {#                                    <label class="col-sm-3 text-left" for="id_tipo_documento">Tipo documento<span class="text-red">* </span></label>#}
                                                <label class="col-sm-3 text-left" for="id_tipo_documento">
                                                    {{ field.label }}{% if field.errors %}
                                                        <span class="text-red">* </span>{% endif %}</label>
                                                <div class=" col-sm-7">

                                                    <div class="related-widget-wrapper"
                                                         data-model-ref="tipo de documento">
                                                        {{ field }}
                                                        {#                                            <select name="tipo_documento" required="" id="id_tipo_documento"#}
                                                        {#                                                    data-select2-id="select2-data-id_tipo_documento" tabindex="-1"#}
                                                        {#                                                    class="select2-hidden-accessible" aria-hidden="true">#}
                                                        {#                                                <option value="" selected="" data-select2-id="select2-data-2-lkcw">#}
                                                        {#                                                    ---------#}
                                                        {#                                                </option>#}
                                                        {##}
                                                        {#                                                <option value="1">Cedula de Identidad</option>#}
                                                        {##}
                                                        {#                                                <option value="2">Registro Único de Contribuyente</option>#}
                                                        {##}
                                                        {#                                            </select>#}
                                                        {#                                            <span class="select2 select2-container select2-container--default"#}
                                                        {#                                                           dir="ltr" data-select2-id="select2-data-1-tnek"#}
                                                        {#                                                           style="width: 279.549px;"><span class="selection"><span#}
                                                        {#                                                class="select2-selection select2-selection--single" role="combobox"#}
                                                        {#                                                aria-haspopup="true" aria-expanded="false" tabindex="0"#}
                                                        {#                                                aria-disabled="false"#}
                                                        {#                                                aria-labelledby="select2-id_tipo_documento-container"#}
                                                        {#                                                aria-controls="select2-id_tipo_documento-container"><span#}
                                                        {#                                                class="select2-selection__rendered"#}
                                                        {#                                                id="select2-id_tipo_documento-container" role="textbox"#}
                                                        {#                                                aria-readonly="true" title="---------">---------</span><span#}
                                                        {#                                                class="select2-selection__arrow" role="presentation"><b#}
                                                        {#                                                role="presentation"></b></span></span></span><span#}
                                                        {#                                                class="dropdown-wrapper" aria-hidden="true"></span></span>#}

                                                        {#                                            <a class="related-widget-wrapper-link change-related"#}
                                                        {#                                               id="change_id_tipo_documento"#}
                                                        {#                                               data-href-template="/admin/turnero_app/tipodedocumento/__fk__/change/?_to_field=id&amp;_popup=1"#}
                                                        {#                                               data-popup="yes" title="Change selected tipo de documento"><img#}
                                                        {#                                                    src="/static/admin/img/icon-changelink.svg" alt="Change"></a><a#}
                                                        {#                                                class="related-widget-wrapper-link add-related"#}
                                                        {#                                                id="add_id_tipo_documento" data-popup="yes"#}
                                                        {#                                                href="/admin/turnero_app/tipodedocumento/add/?_to_field=id&amp;_popup=1"#}
                                                        {#                                                title="Add another tipo de documento"><img#}
                                                        {#                                                src="/static/admin/img/icon-addlink.svg" alt="Add"></a><a#}
                                                        {#                                                class="related-widget-wrapper-link view-related"#}
                                                        {#                                                id="view_id_tipo_documento"#}
                                                        {#                                                data-href-template="/admin/turnero_app/tipodedocumento/__fk__/change/?_to_field=id"#}
                                                        {#                                                title="View selected tipo de documento"><img#}
                                                        {#                                                src="/static/admin/img/icon-viewlink.svg" alt="View"></a>#}

                                                    </div>
                                                    {#<p class="text-danger">{{ field.errors }}</p>#}
                                                    <div class="mt-2">
                                                        <span id="terms-error" class="error invalid-feedback"
                                                              style="display: inline;">{{ field.errors }}</span>
                                                    </div>

                                                    <div class="help-block red">

                                                    </div>

                                                    <div class="help-block text-red">

                                                    </div>
                                                </div>

                                            </div>
                                        </div>
                                    {% endfor %}


                                </div>
                            </div>


                            <script type="text/javascript" id="django-admin-form-add-constants"
                                    src="/static/admin/js/change_form.js" data-model-name="persona"></script>
                            <script id="django-admin-prepopulated-fields-constants"
                                    src="/static/admin/js/prepopulate_init.js"
                                    data-prepopulated-fields="[]">
                            </script>

                        </div>
                        <div class="right">

                            <input type='hidden' name='action' value='registro_form'>
                            <button type="submit" class="btn btn-primary float-right">Guardar</button>
                        </div>
                    </form>

                </div>
            </div>
        </div>

    </div>


{% endblock content2 %}
<!--Termino de la tabla principal -->

    {% block javascript %}
        <script>

        </script>
    {% endblock javascript %}